// Metadados das ações do painel de debug. A lógica de cada ação vive em main.js/mount-game.js
// (só lá tem acesso a combat/rail/session/hud dentro do closure de mountGame) — este módulo só
// descreve o que existe, pra hud.js conseguir montar o painel genericamente.
//
// `category` agrupa as ações em seções colapsáveis no painel (overhaul v0.68.0) — puramente
// organizacional, não afeta a lógica de nenhuma ação. `DEBUG_CATEGORY_ORDER` define a ordem
// de exibição das seções (independente da ordem das ações abaixo, pra poder reorganizar uma
// sem mexer na outra).
export const DEBUG_CATEGORY_ORDER = [
  'Setor & Fluxo',
  'Chefe & Dourado',
  'Combate',
  'Spawns',
  'Jogador',
  'Cartas & Buffs',
  'Esquadrão',
  'Pergunta',
  'Ambiente',
  'Eventos',
  'Testes & Visual',
]

export const DEBUG_ACTIONS = [
  { id: 'restartSector', label: 'Reiniciar setor atual', category: 'Setor & Fluxo' },
  { id: 'nextSector', label: 'Próximo setor', category: 'Setor & Fluxo' },
  { id: 'prevSector', label: 'Setor anterior', category: 'Setor & Fluxo' },
  { id: 'exitArenaNow', label: 'Sair da arena agora', category: 'Setor & Fluxo' },
  { id: 'toggleDisableArena', label: 'Travar/desativar arenas', toggle: true, category: 'Setor & Fluxo' },
  { id: 'nukeEnemies', label: 'Detonar todos os inimigos (Nuke)', category: 'Combate' },
  { id: 'toggleAutoSpawn', label: 'Desligar geração automática de inimigos', toggle: true, category: 'Spawns' },
  { id: 'spawnWave', label: 'Spawnar esquadrão misto', category: 'Spawns' },
  { id: 'grantAllCards', label: 'Conceder todas as cartas', category: 'Cartas & Buffs' },
  { id: 'resetBuffs', label: 'Resetar cartas e buffs', category: 'Cartas & Buffs' },
  { id: 'spawnEnemy', label: 'Spawnar inimigo vermelho', category: 'Spawns' },
  { id: 'spawnTimeEnemy', label: 'Spawnar redutor de tempo', category: 'Spawns' },
  { id: 'spawnBonus', label: 'Spawnar alvo bônus', category: 'Spawns' },
  { id: 'spawnGolden', label: 'Spawnar especial dourado', category: 'Spawns' },
  { id: 'spawnTank', label: 'Spawnar inimigo tanque (5 hp)', category: 'Spawns' },
  { id: 'spawnMiniSwarm', label: 'Spawnar fila de mini-inimigos', category: 'Spawns' },
  { id: 'spawnTimeEnemyMega', label: 'Spawnar ampulheta mega (10 hp, laser)', category: 'Spawns' },
  { id: 'spawnDetrito', label: 'Spawnar detrito (obstáculo)', category: 'Spawns' },
  { id: 'spawnSentinela', label: 'Spawnar sentinela (moldura)', category: 'Spawns' },
  { id: 'spawnReplica', label: 'Spawnar réplica (eco fantasma)', category: 'Spawns' },
  { id: 'spawnFragata', label: 'Spawnar fragata-escudo (arena)', category: 'Spawns' },
  { id: 'spawnVerme', label: 'Spawnar verme-corrente', category: 'Spawns' },
  { id: 'spawnImaSwarm', label: 'Spawnar enxame-ímã', category: 'Spawns' },
  { id: 'spawnSussurro', label: 'Spawnar sussurro (invoca reforço)', category: 'Spawns' },
  { id: 'spawnHorda', label: 'Spawnar horda (atirador grande, se parte em mini-swarms)', category: 'Spawns' },
  { id: 'forceCorrect', label: 'Forçar acerto da pergunta', category: 'Pergunta' },
  { id: 'forceWrong', label: 'Forçar erro da pergunta', category: 'Pergunta' },
  { id: 'addScore', label: '+100 pontos', category: 'Jogador' },
  { id: 'heal', label: 'Curar 1', category: 'Jogador' },
  { id: 'damage', label: 'Causar 1 dano', category: 'Jogador' },
  { id: 'fullHeal', label: 'Recarregar vida ao máximo', category: 'Jogador' },
  { id: 'loseLife', label: 'Perder 1 vida', category: 'Jogador' },
  { id: 'rechargeShield', label: 'Recarregar escudo', category: 'Jogador' },
  { id: 'godMode', label: 'God mode', toggle: true, category: 'Jogador' },
  { id: 'infiniteAmmo', label: 'Tiro infinito', toggle: true, category: 'Jogador' },
  { id: 'dumpPlayerTelemetry', label: 'Imprimir Telemetria do Jogador (console.table)', category: 'Jogador' },
  { id: 'copyPlayerLog', label: 'Copiar Log de Voo do Jogador', category: 'Jogador' },
  { id: 'maxBuffs', label: 'Aplicar buffs máximos', category: 'Cartas & Buffs' },
  { id: 'gotoBoss', label: 'Ir para arena de chefe', category: 'Chefe & Dourado' },
  { id: 'skipToBossFight', label: 'Pular pra luta do chefe', category: 'Chefe & Dourado' },
  { id: 'gotoGolden', label: 'Ir para arena dourada', category: 'Chefe & Dourado' },
  { id: 'clearCombatants', label: 'Limpar inimigos/projéteis', category: 'Combate' },
  { id: 'dumpCombatTelemetry', label: 'Imprimir Telemetria Geral de Combate (Tudo)', category: 'Combate' },
  { id: 'dumpEnemyTelemetry', label: 'Imprimir Telemetria dos Inimigos (console.table)', category: 'Combate' },
  { id: 'copyEnemyLog', label: 'Copiar Log de Combate dos Inimigos', category: 'Combate' },
  { id: 'showHitboxes', label: 'Mostrar hitboxes', toggle: true, category: 'Testes & Visual' },
  { id: 'slowMo', label: 'Câmera lenta (0.25x)', toggle: true, category: 'Testes & Visual' },
  { id: 'giveCard', label: 'Escolher carta roguelike', category: 'Cartas & Buffs' },
  { id: 'triggerFullDodge', label: 'Testar giro/inclinação (1s)', category: 'Testes & Visual' },
  { id: 'fireHomingTest', label: 'Testar tiro teleguiado', category: 'Testes & Visual' },
  { id: 'copyAIValidationLog', label: 'Copiar Log de Validação IA', category: 'Testes & Visual' },
  { id: 'clearAIValidationLog', label: 'Limpar Log de Validação IA', category: 'Testes & Visual' },
  { id: 'toggleManualStep', label: 'Passo a passo (Pausar Loop)', toggle: true, category: 'Testes & Visual' },
  { id: 'step1Frame', label: 'Avançar 1 frame (16.7ms)', category: 'Testes & Visual' },
  { id: 'step10Frames', label: 'Avançar 10 frames (~167ms)', category: 'Testes & Visual' },
  { id: 'step60Frames', label: 'Avançar 60 frames (1s)', category: 'Testes & Visual' },
  { id: 'step180Frames', label: 'Avançar 180 frames (3s)', category: 'Testes & Visual' },
  { id: 'spawnWingman1', label: '+ Wingman 1 (Falco / Interceptor)', category: 'Esquadrão' },
  { id: 'spawnWingman2', label: '+ Wingman 2 (Peppy / Bomber)', category: 'Esquadrão' },
  { id: 'spawnWingman3', label: '+ Wingman 3 (Slippy / Scout)', category: 'Esquadrão' },
  { id: 'spawnWingman4', label: '+ Wingman 4 (Miyu / Stealth)', category: 'Esquadrão' },
  { id: 'clearWingmen', label: 'Dispensar Esquadrão', category: 'Esquadrão' },
  { id: 'dumpWingmanTelemetry', label: 'Imprimir Telemetria no Console (console.table)', category: 'Esquadrão' },
  { id: 'copyWingmanLog', label: 'Copiar Log de Voo dos Aliados', category: 'Esquadrão' },
  { id: 'clearWingmanLog', label: 'Limpar Histórico de Voo', category: 'Esquadrão' },
  { id: 'toggleSkyDome', label: 'Ambiente: Cúpula Nebulosa (SkyDome)', toggle: true, category: 'Ambiente' },
  { id: 'toggleCelestialBodies', label: 'Ambiente: Gigante Gasoso e Lua', toggle: true, category: 'Ambiente' },
  { id: 'toggleMultiLayerStars', label: 'Ambiente: Estrelas Cintilantes', toggle: true, category: 'Ambiente' },
  { id: 'toggleWarpStreaks', label: 'Ambiente: Dobra no Boost (Warp)', toggle: true, category: 'Ambiente' },
  { id: 'toggleNebulaPockets', label: 'Ambiente: Bolsões de Névoa', toggle: true, category: 'Ambiente' },
  { id: 'toggleIonStorms', label: 'Ambiente: Relâmpagos Iônicos', toggle: true, category: 'Ambiente' },
  { id: 'toggleShootingStars', label: 'Ambiente: Meteoros / Cadentes', toggle: true, category: 'Ambiente' },
  { id: 'toggleEnergizedGrid', label: 'Ambiente: Grid Energizado', toggle: true, category: 'Ambiente' },
  { id: 'triggerDebrisStorm', label: 'Evento: Iniciar Tempestade de Detritos', category: 'Eventos' },
  { id: 'toggleDebrisStorm', label: 'Evento: Chuva de Detritos (Auto)', toggle: true, category: 'Eventos' },
  { id: 'spawnTitanic', label: 'Spawnar Detrito Titânico (Colossal)', category: 'Spawns' },
]
